"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class freezeCommand(object):

    __slots__ = ["id"]

    __typenames__ = ["string"]

    __dimensions__ = [None]

    def __init__(self):
        self.id = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(freezeCommand._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __id_encoded = self.id.encode('utf-8')
        buf.write(struct.pack('>I', len(__id_encoded)+1))
        buf.write(__id_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != freezeCommand._get_packed_fingerprint():
            raise ValueError("Decode error")
        return freezeCommand._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = freezeCommand()
        __id_len = struct.unpack('>I', buf.read(4))[0]
        self.id = buf.read(__id_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if freezeCommand in parents: return 0
        tmphash = (0x697dd1f597339c8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if freezeCommand._packed_fingerprint is None:
            freezeCommand._packed_fingerprint = struct.pack(">Q", freezeCommand._get_hash_recursive([]))
        return freezeCommand._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", freezeCommand._get_packed_fingerprint())[0]

