"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class start_stop(object):

    __slots__ = ["start"]

    __typenames__ = ["boolean"]

    __dimensions__ = [None]

    def __init__(self):
        self.start = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(start_stop._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.start))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != start_stop._get_packed_fingerprint():
            raise ValueError("Decode error")
        return start_stop._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = start_stop()
        self.start = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if start_stop in parents: return 0
        tmphash = (0xad85a9aad78eb497) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if start_stop._packed_fingerprint is None:
            start_stop._packed_fingerprint = struct.pack(">Q", start_stop._get_hash_recursive([]))
        return start_stop._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", start_stop._get_packed_fingerprint())[0]

